services:
  
  sis_gudang_app:
    
    build:

      context: .

      dockerfile: Dockerfile

    working_dir: /var/www/sis-gudang-backend

    container_name: sis_gudang_app

    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - .:/var/www
      - ./app/sis-gudang-backend:/var/www/sis-gudang-backend
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    
    networks:
      - sis_gudang_network

  sis_gudang_mysql:

    image: mysql:8.0
      
    container_name: sis_gudang_mysql
      
    restart: unless-stopped
      
    tty: true
      
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sisGudang
      MYSQL_USER: userdocker
      MYSQL_PASSWORD: rootdocker
      
    volumes:
      - ./mysql/sis-gudang-db:/var/lib/mysql
      
    ports:
      - "3306:3306"
      
    networks:
      - sis_gudang_network

  sis_gudang_phpmyadmin:

    image: phpmyadmin/phpmyadmin

    container_name: sis_gudang_phpmyadmin

    restart: unless-stopped

    environment:
      PMA_HOST: sis_gudang_mysql
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3001:80"
    networks:
      - sis_gudang_network

networks:

  sis_gudang_network:
    
    driver: bridge

